## THESE QUESTIONS ARE GUARANTEED TO BE ONLINE GENERATED BY GPT
import datetime
import json
from random import randint, seed


class Question:
    def __init__(self, id, text):
        self.dict = {"id": id, "text": text}

    def get(self):
        return self.dict


class QuestionList:
    def __init__(self):
        self.questions = []
        self.last_hrs = 0
        self.last_mins = 0

    def add_question(self, question):
        self.questions.append(question)

    def get_n_questions(self, N):
        if N > len(self.questions):
            raise ValueError("Don't ask for more questions than we have pls")
        numbers = set()

        while len(numbers) < N:
            numbers.add(randint(0, len(self.questions) - 1))

        questions_out = [self.questions[number].get() for number in numbers]

        # questions_out = []

        # for number in numbers :
        #     questions_out.append(self.questions[number])

        return questions_out

    def get_n_question_dict(self, N):
        qs = self.get_n_questions(N)
        return {"questions": qs}

    def pulse(self):
        # sketchy but ok, careful if you consume this
        time = datetime.datetime.utcnow()
        hours, mins = time.hour, (time.minute/10)
        if hours != self.last_hrs or mins != self.last_mins:
            self.last_hrs = hours
            self.last_mins = mins
        seed(6 * hours + mins)


# It's online because it says so
QUESTIONS_LIST = QuestionList()
QUESTIONS_LIST.add_question(Question(0, "What's your biggest goal in life?"))
QUESTIONS_LIST.add_question(Question(1, "What's your greatest weakness?"))
QUESTIONS_LIST.add_question(Question(2, "Which comes first: milk or cereal?"))
QUESTIONS_LIST.add_question(
    Question(
        3,
        "What are your thoughts on universal basic income?",
    )
)
QUESTIONS_LIST.add_question(Question(4, "Lord of the Rings or Harry Potter?"))
QUESTIONS_LIST.add_question(Question(5, "Would you like to be famous? In what way?"))
QUESTIONS_LIST.add_question(Question(6, "What is your superpower?"))
QUESTIONS_LIST.add_question(Question(7, "What is the greatest challenge facing society today?"))
QUESTIONS_LIST.add_question(Question(8, "What are your thoughts on gun control?"))
QUESTIONS_LIST.add_question(Question(9, "How can we, as a society, decrease inequality?"))
QUESTIONS_LIST.add_question(Question(10, "How can we, as a society, decrease polarization?"))
QUESTIONS_LIST.add_question(Question(11, "How many holes does a straw have?"))
QUESTIONS_LIST.add_question(Question(12, "Is water wet?"))
QUESTIONS_LIST.add_question(Question(13, "How do you unwind?"))
QUESTIONS_LIST.add_question(Question(14, "Is social media good for society?"))

# "questions": [
#                 {"id": 0,
#                 "text": "What's your biggest goal in life?"},
#                 {"id": 1, "text": "What's your greatest weakness?"},
#                 {"id": 2, "text": "Which comes first: milk or cereal?"},
#             ]